FROM gradle:6.0.1-jdk11 AS build

WORKDIR /app

# Restore maven dependencies in a separate build step
COPY build.gradle .

COPY src src
COPY mockData mockData
RUN gradle build


FROM openjdk:11-jre-slim

WORKDIR /app

COPY src src
COPY mockData mockData
COPY --from=build /app/build build
RUN ls ./build/libs/

CMD ["java", "-cp", "build/libs/app-all.jar", "de.hpi.datastreams.apps.ServerAppRunner"]
